Web/MiddleMan.Web/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using MiddleMan.Services.Interfaces;
using MiddleMan.Web.Hubs;
using MiddleMan.Web.ViewModels.InputModels.Message;
using MiddleMan.Web.ViewModels.ViewModels.Messages;

namespace MiddleMan.Web.Controllers
{
    public class MessagesController : Controller
    {
        private readonly IMessagesService messagesService;
        private readonly IOfferService offerService;
        private readonly IUserService userService;
        private readonly IHubContext<MessageHub> hubContext;

        public MessagesController(
            IMessagesService messagesService,
            IOfferService offerService,
            IUserService userService,
            IHubContext<MessageHub> hubContext)
        {
            this.messagesService = messagesService;
            this.offerService = offerService;
            this.userService = userService;
            this.hubContext = hubContext;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var inboxMessagesViewModels = await this.messagesService.GetInboxMessagesAsync();

            return this.View(inboxMessagesViewModels);
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Send(SendMessageInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                var sendMessageBindingModel =
                    await this.messagesService.GetMessageBindingModelByOfferIdAsync(inputModel.OfferId);
                sendMessageBindingModel.InputModel = inputModel;

                return this.View(sendMessageBindingModel);
            }

            var unreadMessagesCount = await this.messagesService.GetUnreadMessagesCountAsync(inputModel.RecipientId);

            await this.hubContext.Clients.User(inputModel.RecipientId).SendAsync("MessageCount", unreadMessagesCount);

            if (this.ModelState.IsValid)
            {
                var messageViewModel = await this.messagesService.CreateMessageAsync(inputModel.SenderId, inputModel.RecipientId, inputModel.OfferId, inputModel.Content);
                await this.hubContext.Clients.User(inputModel.RecipientId)
                    .SendAsync("SendMessage", messageViewModel);
            }

            return this.RedirectToAction("Details", new { offerId = inputModel.OfferId, senderId = inputModel.RecipientId, recipientId = inputModel.SenderId });
        }

        [Authorize]
        public async Task<IActionResult> Details(MessagesDetailsViewModel viewModel)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (viewModel.SenderId != userId)
            {
                return this.Redirect("/Messages");
            }

            var messagesViewModel = new List<MessageViewModel>();

            var messages = await this.messagesService.GetMessagesForOfferAsync(viewModel.OfferId, viewModel.SenderId, viewModel.RecipientId);
            messages.OrderBy(date => date.CreatedOn);

            var sideAId = viewModel.SenderId;
            var sideBId = viewModel.RecipientId;

            await this.messagesService.MarkAsSeenForUserAsync(viewModel.SenderId, viewModel.OfferId);

            viewModel.SideA = new UserMessagesViewModel()
            {
                ProfilePicUrl = await this.userService.GetUserProfilePictureUrlAsync(sideAId),
                Username = await this.userService.GetUsernameByIdAsync(sideAId),
            };

            viewModel.SideB = new UserMessagesViewModel()
            {
                ProfilePicUrl = await this.userService.GetUserProfilePictureUrlAsync(sideBId),
                Username = await this.userService.GetUsernameByIdAsync(sideBId),
            };

            foreach (var message in messages)
            {
                messagesViewModel.Add(new MessageViewModel()
                {
                    Content = message.Content,
                    IsRead = message.IsRead,
                    RecipientId = message.RecipientId,
                    SenderId = message.SenderId,
                    SentOn = message.CreatedOn.ToString("MM/dd hh:mm tt"),
                    OfferId = message.OfferId,
                    Sender = await this.userService.GetUsernameByIdAsync(message.SenderId),
                });
            }

            viewModel.Messages = messagesViewModel;
            viewModel.OfferTitle = await this.offerService.GetOfferNameById(viewModel.OfferId);
            viewModel.InputModel = new SendMessageInputModel()
            {
                SenderId = viewModel.SenderId,
                OfferId = viewModel.OfferId,
                RecipientId = viewModel.RecipientId,
            };

            return this.View(viewModel);
        }
    }
}

Web/MiddleMan.Web/Controllers/OfferController.cs
namespace MiddleMan.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using MiddleMan.Common;
    using MiddleMan.Data.Common.Repositories;
    using MiddleMan.Data.Models;
    using MiddleMan.Services;
    using MiddleMan.Services.Data;
    using MiddleMan.Services.Interfaces;
    using MiddleMan.Web.ViewModels.Administration.Dashboard.InputModels;
    using MiddleMan.Web.ViewModels.InputModels;
    using MiddleMan.Web.ViewModels.InputModels.Offer;
    using MiddleMan.Web.ViewModels.Search;
    using MiddleMan.Web.ViewModels.ViewModels;
    using MiddleMan.Web.ViewModels.ViewModels.Comment;
    using MiddleMan.Web.ViewModels.ViewModels.Offer;
    using MiddleMan.Web.ViewModels.ViewModels.Search;

    public class OfferController : BaseController
    {
        private readonly IOfferService offerService;

        private readonly ICategoryService categoryService;

        private readonly ICloudinaryService cloudinaryService;

        private readonly ICommentService commentService;

        private readonly IUserService userService;

        public OfferController(
            IOfferService offerService,
            ICategoryService categoryService,
            ICloudinaryService cloudinaryService,
            ICommentService commentService,
            IUserService userService)
        {
            this.offerService = offerService;  // todo rename sell to offer or revert
            this.categoryService = categoryService;
            this.cloudinaryService = cloudinaryService;
            this.commentService = commentService;
            this.userService = userService;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var categories = await this.categoryService.GetAllCategoryViewModelsAsync();

            CreateOfferSharedModel viewModel = new CreateOfferSharedModel();
            viewModel.CreateOfferViewModel = new CreateOfferViewModel(categories);
            return this.View(viewModel);
        }

        public async Task<IActionResult> CreateOffer(CreateOfferSharedModel inputModel) // index post requsest for create
        {
            if (!this.ModelState.IsValid)
            {
                return this.Redirect("/Offer");
            }

            var imgSize = inputModel.CreateOfferModel.Photo.Length;

            if (imgSize >= 1048576)
            {
                return this.Redirect("/Offer");
            }

            var offerInput = inputModel.CreateOfferModel;
            var categoryId = await this.categoryService.GetIdByNameAsync(offerInput.CategotyName);
            offerInput.CategotyName = categoryId;
            offerInput.CreatorId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            var photoUrl = await this.cloudinaryService.UploadPhotoAsync(
                offerInput.Photo,
                $"{userId}-{offerInput.Name}",
                GlobalConstants.CloudFolderForOfferPhotos);
            offerInput.PicUrl = photoUrl;

            await this.offerService.CreateOfferAsync(offerInput);

            return this.Redirect("/");
        }

        public async Task<IActionResult> Details(string id)
        {
            var offer = await this.offerService.GetOfferByIdAsync(id);

            if (offer != null)
            {
                var categories = await this.categoryService.GetAllCategoryViewModelsAsync();
                var category = await this.categoryService.GetCategoryNameByIdAsync(offer.CategoryId);
                var comments = await this.commentService.GetOfferCommentsAsync(id);
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var rated = await this.offerService.IsOfferRatedAsync(offer.Id, userId);
                double offerRating = await this.offerService.GetOfferRatingAsync(id);
                string startsStringRating = this.offerService.StartsStringRating(offerRating);

                int? offerRatedByUser = null;
                try
                {
                    offerRatedByUser = await this.offerService.GetRateForOffer(offer.Id, userId);
                }
                catch (Exception)
                {
                }

                var offerView = new OfferViewModelDetails()
                {
                    CreatorId = offer.CreatorId,
                    CreatorName = this.userService.GetUserByIdAsync(offer.CreatorId).Result.UserName,
                    Description = offer.Description,
                    Name = offer.Name,
                    PicUrl = offer.PicUrl,
                    Price = offer.Price,
                    CreatedOn = offer.CreatedOn,
                    Id = offer.Id,
                    Rated = rated,
                    OfferRating = offerRating,
                    StartsStringRating = startsStringRating,
                    IsFavoritedByUser = await this.userService.IsOfferFavoritedByUserAsync(offer.Id, userId),
                };

                foreach (var comment in comments)
                {
                    offerView.Comments.Add(new CommentViewModel()
                    {
                        CreatedOn = comment.CreatedOn.ToString("dd/M/yy H:mm"),
                        CreatorName = await this.userService.GetUsernameByIdAsync(comment.CreatorId),
                        Description = comment.Description,
                        CreatorId = comment.CreatorId,
                    });
                }

                var detailsModel = new DetailsViewModel()
                {
                    CategoryName = category,
                    Categories = categories,
                    Offer = offerView,
                    CategoryId = offer.CategoryId,
                    UserRated = offerRatedByUser,
                    IsOwner = offer.CreatorId == userId ? true : false,
                };

                return this.View(detailsModel);
            }

            return this.NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> AddReview(CreateReviewModel commentInputModel, string id) // index post requsest for create
        {
            if (!this.ModelState.IsValid)
            {
                return this.Redirect($"/Offer/Edit?id={id}");
            }

            commentInputModel.CreatorId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            commentInputModel.Id = id;

            await this.commentService.AddReviewToOffer(commentInputModel);

            return this.Redirect($"/Offer/Details?id={commentInputModel.Id}");
        }

        public async Task<IActionResult> Edit(string id)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (!await this.offerService.IsUserCreatorOfOfferAsync(userId, id))
            {
                return this.Redirect($"/Offer/Details?id={id}");
            }

            var categories = await this.categoryService.GetAllCategoryViewModelsAsync();
            var offer = await this.offerService.GetOfferByIdAsync(id);
            var category = await this.categoryService.GetCategoryNameByIdAsync(offer.CategoryId);
            var comments = await this.commentService.GetOfferCommentsAsync(id);
            var rated = await this.offerService.IsOfferRatedAsync(offer.Id, userId);
            double offerRating = await this.offerService.GetOfferRatingAsync(id);
            string startsStringRating = this.offerService.StartsStringRating(offerRating);

            int? offerRatedByUser = null;
            try
            {
                offerRatedByUser = await this.offerService.GetRateForOffer(offer.Id, userId);
            }
            catch (Exception)
            {
            }

            var offerView = new OfferViewModelDetails()
            {
                CreatorId = offer.CreatorId,
                Description = offer.Description,
                Name = offer.Name,
                PicUrl = offer.PicUrl,
                Price = offer.Price,
                CreatedOn = offer.CreatedOn,
                Id = offer.Id,
                Rated = rated,
                OfferRating = offerRating,
                StartsStringRating = startsStringRating,
                BuyContent = offer.BuyContent,
            };

            foreach (var comment in comments)
            {
                offerView.Comments.Add(new CommentViewModel()
                {
                    CreatedOn = comment.CreatedOn.ToString("dd/M/yy H:mm"),
                    CreatorName = await this.userService.GetUsernameByIdAsync(comment.CreatorId),
                    Description = comment.Description,
                    CreatorId = comment.CreatorId,
                });
            }

            var detailsModel = new EditViewModel()
            {
                CategoryName = category,
                Categories = categories,
                Offer = offerView,
                CategoryId = offer.CategoryId,
                BuyContent = offer.BuyContent,
            };

            return this.View(detailsModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, EditOfferModel inputModel) // index post requsest for create
        {
            if (!this.ModelState.IsValid)
            {
                return this.Redirect($"/Offer/Edit?id={id}");
            }

            var offerInput = inputModel;
            var imgSize = offerInput.Photo != null ? inputModel.Photo.Length : 1;

            if (imgSize >= 1048576)
            {
                return this.Redirect($"/Offer/Edit?id={id}");
            }

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

Web/MiddleMan.Web/Views/Messages/Details.cshtml
@model MessagesDetailsViewModel
@inject IUserService UsersService

@{
    ViewData["Title"] = $"Chat - {Model.SideB.Username}";
    var currentUserId = UsersService.GetCurrentUserId();
}

<h3 class="text-center mb-4"><a asp-controller="Offer" asp-action="Details" asp-route-id="@Model.OfferId">@Model.OfferTitle</a></h3>
<div id="messages" style="height: 500px; overflow-y: auto;">
    @foreach (var message in Model.Messages)
    {
        <div class="card-body msg_card_body">
            <p>
                @if (message.Sender == User.Identity.Name)
                {
                    <div class="d-flex justify-content-end mb-4">
                        <div class="msg_cotainer_send">
                            @message.Content
                            <span class="msg_time_send">@message.SentOn</span>
                        </div>
                        <div class="img_cont_msg">
                            <img src="@Model.SideA.ProfilePicUrl" class="rounded-circle user_img_msg" />
                        </div>
                    </div>
                }
                else
                {
                    <div class="d-flex justify-content-start mb-4">
                        <div class="img_cont_msg">
                            <img src="@Model.SideB.ProfilePicUrl" class="rounded-circle user_img_msg">
                        </div>
                        <div class="msg_cotainer">
                            @message.Content
                            <span class="msg_time">@message.SentOn</span>
                        </div>
                    </div>
                }
            </p>
        </div>
    }
</div>
<div class="row">
    <div class="offset-2 col-8">
        <vc:send-message-component view-model="@Model.InputModel">
        </vc:send-message-component>
    </div>
</div>

@section Scripts{
    <script src="~/js/message-signalr.js" asp-append-version="true"></script>
    <script>
        var heigh = document.documentElement.clientHeight - 300;
        var messages = document.getElementById("messages");
        messages.style.height = heigh.toString() + "px";

        function scrollToBottom() {
            messages.scrollTop = messages.scrollHeight;
        }

        scrollToBottom();
    </script>
}

Web/MiddleMan.Web/Views/Messages/Index.cshtml
@model List<MessageViewModel>
@{
    ViewData["Title"] = "Inbox";
}

<h3 class="text-center">Inbox:</h3>
<hr class="hr-sell-me" />
<div class="card text-center">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            
        </ul>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">From</th>
                        <th scope="col">Last Message</th>
                        <th scope="col">Offer Title</th>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var message in Model)
                    {
                        var messageParams = new Dictionary<string, string>
                                            {
                        {"recipientId", message.RecipientId},
                        {"senderId", message.SenderId},
                        {"offerId", message.OfferId}
                    };

                    <tr class="message-tr" onclick="location.href='/Messages/Details?offerId=@messageParams["offerId"]&senderId=@messageParams["senderId"]&recipientId=@messageParams["recipientId"]'">
                        @{string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); }

                        @if (!message.IsRead && message.MessageForId == userId)
                        {
                            <th>@message.Sender</th>
                            <td style="font-weight: bold;">@message.LastMessage</td>
                            <th><a asp-controller="Messages" asp-action="Details" asp-all-route-data="messageParams">@message.OfferTitle</a></th>
                            <th>@message.SentOn</th>
                        }
                        else
                        {
                            <td>@message.Sender</td>
                            <td>@message.LastMessage</td>
                            <td><a asp-controller="Messages" asp-action="Details" asp-all-route-data="messageParams">@message.OfferTitle</a></td>
                            <td>@message.SentOn</td>
                        }
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>